version: "3.9"

services:
  app:
    build: .
    container_name: todo_container
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    tty: true
    command: go run main.go
    restart: on-failure
    depends_on:
      - postgresdb
    networks:
      - learning

  postgresdb:
    image: postgres:alpine
    restart: always
    container_name: tododb_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
      - postgres-db:/var/lib/postgresql/data
    networks:
      - learning

volumes:
  postgres-db:
    driver: local
networks:
  learning:
    driver: bridge